on: push
name: Deploy the BIM Whale
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.2
            - name: Prepare
              run: |
                  sudo touch public/.ftp-deploy-sync-state.json
                  sudo chmod 777 public/.ftp-deploy-sync-state.json
            - name: Sync Files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: ftpcluster.loopia.se
                  username: bim-whale-github-actions-ftp
                  password: ${{ secrets.password }}
                  local-dir: public/
                  server-dir: public_html/
